buble/buble/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
     document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
     document_root = settings.STATIC_ROOT)

buble/gum/urls.py
from django import views
from django.urls import path

from . import views

app_name = 'gum'

urlpatterns = [
    path('index', views.index, name='index'),
    path('regform', views.regform, name='regform'),
    path('base', views.base, name='base'),
    path('all_posts/', views.PostView.as_view(), name='all_posts'),
    path('crud_form/', views.crud_form, name='crud_form'),
    path('<int:pk>', views.DetailPost.as_view(), name='detail'),
    path('<int:pk>/update', views.UpDate.as_view(), name='update'),
    path('<int:pk>/delete', views.DeletePost.as_view(), name='delete'),
    path('', views.HomeView.as_view(), name='home'),
    
    
]

buble/gum/models.py
from django.db import models


# Create your models here.


class CreateUsers(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField( unique=True, max_length=50)
    password = models.CharField( max_length=30)
    mail = models.EmailField( max_length=50)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self) -> str:
        return f'title : {self.name} , id : {self.id}'




class CreatePost(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='post_img',blank=True)
    message = models.TextField(max_length=1000)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['id']

    def __str__(self) -> str:
        return f'title : {self.title} id : {self.id}'

    
    def get_absolute_url(self):
        return  f'/all_posts'

buble/gum/forms.py
from django import forms


class LoginForm(forms.Form):
    name = forms.CharField(label='Имя пользователя', required=True)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(), required=True)
    mail = forms.EmailField(label='Электронная почта', required=True)


class PostForm(forms.Form):
    title = forms.CharField(label='Заголовок',max_length=100)
    message = forms.CharField(label='Пост',max_length=1000, widget=forms.Textarea())
    author = forms.CharField(label='Автор',max_length=30)

buble/gum/views.py
from re import template
from django.views.generic import DetailView, UpdateView, DeleteView,ListView
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import LoginForm
from .models import CreatePost
from .forms import PostForm


# Create your views here.

def index(request):
    return HttpResponse('Hello world')


def regform(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
    form = LoginForm()
    return render(request, 'regforms.html', {'form': form})


def base(request):
    return render(request, 'base.html') 


def crud_form(request):
    if request.method == "POST":
        form_post = PostForm(request.POST)
        if form_post.is_valid():
            create_post = CreatePost()
            create_post.title = form_post.cleaned_data['title']
            create_post.message = form_post.cleaned_data['message']
            create_post.author = form_post.cleaned_data['author']
            create_post.save()
            print(form_post.cleaned_data)
            return redirect('gum:all_posts')
    form_post = PostForm()

    data = {
        'form': form_post
    }
   
    return render(request, 'crud_form.html',  data)


class PostView(ListView):
    paginate_by = 3
    model = CreatePost
    template_name = 'all_posts.html'
    context_object_name = 'all_posts'


class DetailPost(DetailView):
    model = CreatePost
    template_name = 'detail.html'
    context_object_name = 'post'
    

class UpDate(UpdateView):
    model = CreatePost
    template_name = 'solution.html'
    fields = ['title', 'message']

class DeletePost(DeleteView):
    model = CreatePost
    template_name = 'delete_post.html'
    fields = ['title', 'message']
    success_url = '/all_posts/'

class HomeView(ListView):
    model = CreatePost
    template_name = 'home.html'
    context_object_name = 'all_posts'
    queryset = CreatePost.objects.all()[:4]


# def all_posts(request):

#     pub_posts = CreatePost.objects.all()

#     return render(request, 'all_posts.html', {'all_posts':pub_posts})


# def detail_post(request, str):
#     detail = CreatePost.objects.all().filter(id=str)

#     data = {
#         'post': detail
#     }
#     return render(request, 'detail.html', data )

buble/gum/templates/all_posts.html
{% extends 'base.html' %}

{% block title %} {{post.title}} {% endblock %}

{% block all_posts %}

    <div class="conteiner">
        <div class="row">
            <div class="col-md-10">

                {% for post in all_posts %}
                <h5>{{post.title}}</h3>
                <p>{{post.author}}</p>
                <b>{{post.pub_date}}</b>
                <p><a href="{% url 'gum:detail' post.id %}" class="btn btn-primary">Подробнее</a></p>
                <div>-------</div>
                {% endfor %}
            
            </div>
        </div>
    </div>
     
{% endblock %}

buble/gum/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
     crossorigin="anonymous">
     
    <link  rel = "shortcut icon"  type = "image/png"  href = "{% static 'images/boar.png' %}" /> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    
    <title>Base view</title>

</head>
<body> 

  <div class="wraper conteiner">
    <div class="row">
      <div class="col">

        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'gum:home' %}">
              <font style="vertical-align: inherit;">Boar</font></a>
  
            <button class="navbar-toggler" type="button" 
            data-bs-toggle="collapse" data-bs-target="#navbarCollapse" 
            aria-controls="navbarCollapse" aria-expanded="false" 
            aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
  
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'gum:all_posts' %}">
                    <font style="vertical-align: inherit;"> Все посты </font></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'gum:crud_form' %}">
                    <font style="vertical-align: inherit;">Создать пост </font></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled">
                    <font style="vertical-align: inherit;"> В разработке </font></a>
                </li>
              </ul>
              <form class="d-flex">
                <input class="form-control me-2" 
                type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">
                  <font style="vertical-align: inherit;">Поиск </font></button>
              </form>
            </div>
          </div>
        </nav>
  
        <div class="conteiner pt-5 ">
          <div class="row justify-content-center  my-4">
            <div class="col-4 text-center">

              {% block all_posts %}
              {% endblock %}

              {% block crud %}
              {% endblock %}

              {% block detail %}
              {% endblock %}

              {% block delete %}
              {% endblock %}



              {% block solution %}
              {% endblock %}

              {% block home %}
              {% endblock %}

              <nav aria-label="base pagination col-8">
                  <ul class="pagination justify-content-center">

                    {% if page_obj.has_previous %}

                    <li class="page-item">
                      <a href="?page={{page_obj.previous_page_number}}" class="page-link rounded-circle my-2 mx-auto">&lt;</a>
                    </li>

                    {% endif %}

                    {% for pagination in paginator.page_range %}
                    {% if page_obj.number == pagination %}

                    <li class="page-item active "  aria-current="page"><a href="http://" class="page-link rounded-circle my-2 mx-auto">{{pagination}}</a></li>

                    {% elif pagination >= page_obj.number|add:-2 and pagination <= page_obj.number|add:2  %}
                    
                    <li class="page-item">
                      <a href="?page={{pagination}}" class="page-link rounded-circle my-2 mx-auto">{{pagination}}</a>
                    </li>

                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}

                    <li class="page-item">
                      <a href="?page={{page_obj.next_page_number}}" class="page-link rounded-circle my-2 mx-auto">&gt;</a>
                    </li>

                    {% endif %}

                  </ul>
              </nav>



            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
    crossorigin="anonymous">
  </script>  

</body>
</html>

buble/gum/templates/crud_form.html
{% extends 'base.html' %}

{% block crud %}

        <div class="conteiner d-flex">
            <div class="row">
                <div class="col-12">

                    <form action=" "method="post" class="form-control">

                        {{form.as_p}}
                        {%csrf_token%}
            
                        <button type="submit" class="btn btn-success">Создать пост</button>
                    </form>

                </div>
            </div>
        </div>
       
{%endblock%}

buble/gum/templates/delete_post.html
{% extends 'base.html' %}

{% block title %} Удаление статьи {% endblock %}

{% block delete %}
  
    <div class="conteiner">
        <form action=" "method="post" class="form-control">

            {%csrf_token%}

            <button type="submit" class="btn btn-warning">Удалить статью</button>
        </form>  
    </div>
    
{% endblock %}

buble/gum/templates/detail.html
{% extends 'base.html' %}

{% block title %} {{post.title}} {% endblock %}


{% block detail %}
        <div class="conteiner">
                <div class="row col-md-8">

                        <h5>{{post.title}}</h5>
                        {%if post.image%}
                        <img src="{{post.image.url}}" alt="PICTURE">
                        {%endif%}
                        <p>{{post.message}}</p>
                        <p>{{post.author}}</p>
                        <b>{{post.pub_date}}</b>
                        <div>-------</div>

                        <a href="{% url 'gum:delete' post.id %}" class="btn btn-danger">Удалить статью</a>
                        <a href="{% url 'gum:update' post.id %}" class="btn btn-warning mt-2">Обновить статью</a>
                </div>
        </div>
        


{% endblock %}

buble/gum/templates/home.html
{% extends 'base.html' %}

{% block title %} {{post.title}} {% endblock %}

{% block home %}

    <div class="conteiner">
        <div class="row">
            <div class="col-md-8">

                {% for post in all_posts %}
                <h5>{{post.title}}</h3>
                <p>{{post.author}}</p>
                <p><a href="{% url 'gum:detail' post.id %}" class="btn btn-link">Подробнее</a></p>
                <div>-------</div>
                {% endfor %}
            
            </div>
        </div>
    </div>
     
{% endblock %}

buble/gum/templates/regforms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit"value='Submit'>
    </form>
</body>
</html>

buble/gum/templates/solution.html
{% extends 'base.html' %}


{% block solution %}

<div class="conteiner d-flex">
    <div class="row">
        <div class="col-12">

            <form action=" "method="post" class="form-control">

                {{form.as_p}}
                {%csrf_token%}
    
                <button type="submit" class="btn btn-success">Обновить пост</button>
            </form>

        </div>
    </div>
</div>

{% endblock %}